/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : string,
  'status' : AppointmentStatus,
  'doctorId' : string,
  'patientId' : UserId,
  'date' : string,
  'createdAt' : Timestamp,
  'slot' : string,
  'hospitalId' : string,
  'notes' : [] | [string],
  'department' : string,
}
export type AppointmentStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface Blog {
  'id' : string,
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'publishDate' : string,
  'author' : string,
  'imageUrl' : [] | [string],
  'excerpt' : string,
  'category' : string,
}
export interface Doctor {
  'id' : string,
  'bio' : string,
  'hospitalIds' : Array<string>,
  'userId' : UserId,
  'name' : string,
  'qualifications' : string,
  'speciality' : string,
  'experience' : bigint,
  'imageUrl' : [] | [string],
  'availableSlots' : Array<TimeSlot>,
  'rating' : number,
}
export interface HealthPackage {
  'id' : string,
  'tests' : Array<string>,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'category' : string,
  'price' : bigint,
}
export interface Hospital {
  'id' : string,
  'emergency' : string,
  'city' : string,
  'name' : string,
  'state' : string,
  'imageUrl' : [] | [string],
  'address' : string,
  'facilities' : Array<string>,
  'phone' : string,
  'doctorIds' : Array<string>,
}
export interface MenstrualCycle {
  'id' : string,
  'patientId' : UserId,
  'notes' : [] | [string],
  'cycleLength' : bigint,
  'symptoms' : Array<string>,
  'startDate' : string,
}
export interface PregnancyData {
  'id' : string,
  'patientId' : UserId,
  'lastUpdated' : Timestamp,
  'currentWeek' : bigint,
  'notes' : Array<WeekNote>,
  'startDate' : string,
}
export interface Report {
  'id' : string,
  'doctorId' : string,
  'patientId' : UserId,
  'date' : string,
  'fileName' : string,
  'reportType' : string,
  'notes' : [] | [string],
  'fileRef' : string,
}
export interface Testimonial {
  'id' : string,
  'content' : string,
  'patientName' : string,
  'rating' : bigint,
  'department' : string,
}
export interface TimeSlot {
  'id' : string,
  'day' : string,
  'startTime' : string,
  'endTime' : string,
  'isAvailable' : boolean,
}
export type Timestamp = bigint;
export interface User {
  'id' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : string,
  'abhaId' : [] | [string],
  'phone' : string,
}
export type UserId = string;
export type UserRole = { 'patient' : null } |
  { 'admin' : null } |
  { 'doctor' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeekNote {
  'scanImageRef' : [] | [string],
  'note' : string,
  'week' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addMenstrualCycle' : ActorMethod<
    [string, bigint, Array<string>, [] | [string]],
    string
  >,
  'addTestimonial' : ActorMethod<[Testimonial], boolean>,
  'addWeekNote' : ActorMethod<[bigint, string, [] | [string]], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'bookAppointment' : ActorMethod<
    [string, string, string, string, string, [] | [string]],
    string
  >,
  'cancelAppointment' : ActorMethod<[string], boolean>,
  'createBlog' : ActorMethod<[Blog], boolean>,
  'createDoctor' : ActorMethod<[Doctor], boolean>,
  'createHealthPackage' : ActorMethod<[HealthPackage], boolean>,
  'createHospital' : ActorMethod<[Hospital], boolean>,
  'deleteBlog' : ActorMethod<[string], boolean>,
  'deleteDoctor' : ActorMethod<[string], boolean>,
  'deleteHospital' : ActorMethod<[string], boolean>,
  'deleteTestimonial' : ActorMethod<[string], boolean>,
  'getAppointmentById' : ActorMethod<[string], [] | [Appointment]>,
  'getBlogById' : ActorMethod<[string], [] | [Blog]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getDoctorById' : ActorMethod<[string], [] | [Doctor]>,
  'getHealthPackage' : ActorMethod<[string], [] | [HealthPackage]>,
  'getHospitalById' : ActorMethod<[string], [] | [Hospital]>,
  'getMyPregnancyData' : ActorMethod<[], [] | [PregnancyData]>,
  'getMyProfile' : ActorMethod<[], [] | [User]>,
  'getReport' : ActorMethod<[string], [] | [Report]>,
  'getUserById' : ActorMethod<[UserId], [] | [User]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'listAllBlogs' : ActorMethod<[], Array<Blog>>,
  'listAllUsers' : ActorMethod<[], Array<User>>,
  'listAppointmentsByDoctor' : ActorMethod<[string], Array<Appointment>>,
  'listDoctors' : ActorMethod<[], Array<Doctor>>,
  'listDoctorsByHospital' : ActorMethod<[string], Array<Doctor>>,
  'listDoctorsBySpeciality' : ActorMethod<[string], Array<Doctor>>,
  'listHealthPackages' : ActorMethod<[], Array<HealthPackage>>,
  'listHospitals' : ActorMethod<[], Array<Hospital>>,
  'listHospitalsByCity' : ActorMethod<[string], Array<Hospital>>,
  'listMyAppointments' : ActorMethod<[], Array<Appointment>>,
  'listMyMenstrualCycles' : ActorMethod<[], Array<MenstrualCycle>>,
  'listMyReports' : ActorMethod<[], Array<Report>>,
  'listPublishedBlogs' : ActorMethod<[], Array<Blog>>,
  'listTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'listUsersByRole' : ActorMethod<[UserRole], Array<User>>,
  'registerUser' : ActorMethod<
    [string, string, string, UserRole, [] | [string]],
    string
  >,
  'updateAppointmentStatus' : ActorMethod<[string, AppointmentStatus], boolean>,
  'updateBlog' : ActorMethod<[Blog], boolean>,
  'updateDoctor' : ActorMethod<[Doctor], boolean>,
  'updateHealthPackage' : ActorMethod<[HealthPackage], boolean>,
  'updateHospital' : ActorMethod<[Hospital], boolean>,
  'updateMenstrualCycle' : ActorMethod<[MenstrualCycle], boolean>,
  'updateMyProfile' : ActorMethod<[string, string, [] | [string]], boolean>,
  'updateSlotAvailability' : ActorMethod<[string, string, boolean], boolean>,
  'uploadReport' : ActorMethod<[Report], boolean>,
  'upsertPregnancyData' : ActorMethod<[bigint, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];