/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Testimonial = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'patientName' : IDL.Text,
  'rating' : IDL.Nat,
  'department' : IDL.Text,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Blog = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'publishDate' : IDL.Text,
  'author' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const UserId = IDL.Text;
export const TimeSlot = IDL.Record({
  'id' : IDL.Text,
  'day' : IDL.Text,
  'startTime' : IDL.Text,
  'endTime' : IDL.Text,
  'isAvailable' : IDL.Bool,
});
export const Doctor = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'hospitalIds' : IDL.Vec(IDL.Text),
  'userId' : UserId,
  'name' : IDL.Text,
  'qualifications' : IDL.Text,
  'speciality' : IDL.Text,
  'experience' : IDL.Nat,
  'imageUrl' : IDL.Opt(IDL.Text),
  'availableSlots' : IDL.Vec(TimeSlot),
  'rating' : IDL.Float64,
});
export const HealthPackage = IDL.Record({
  'id' : IDL.Text,
  'tests' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const Hospital = IDL.Record({
  'id' : IDL.Text,
  'emergency' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'state' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'address' : IDL.Text,
  'facilities' : IDL.Vec(IDL.Text),
  'phone' : IDL.Text,
  'doctorIds' : IDL.Vec(IDL.Text),
});
export const AppointmentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Appointment = IDL.Record({
  'id' : IDL.Text,
  'status' : AppointmentStatus,
  'doctorId' : IDL.Text,
  'patientId' : UserId,
  'date' : IDL.Text,
  'createdAt' : Timestamp,
  'slot' : IDL.Text,
  'hospitalId' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'department' : IDL.Text,
});
export const WeekNote = IDL.Record({
  'scanImageRef' : IDL.Opt(IDL.Text),
  'note' : IDL.Text,
  'week' : IDL.Nat,
});
export const PregnancyData = IDL.Record({
  'id' : IDL.Text,
  'patientId' : UserId,
  'lastUpdated' : Timestamp,
  'currentWeek' : IDL.Nat,
  'notes' : IDL.Vec(WeekNote),
  'startDate' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'patient' : IDL.Null,
  'admin' : IDL.Null,
  'doctor' : IDL.Null,
});
export const User = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : IDL.Text,
  'abhaId' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
});
export const Report = IDL.Record({
  'id' : IDL.Text,
  'doctorId' : IDL.Text,
  'patientId' : UserId,
  'date' : IDL.Text,
  'fileName' : IDL.Text,
  'reportType' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'fileRef' : IDL.Text,
});
export const MenstrualCycle = IDL.Record({
  'id' : IDL.Text,
  'patientId' : UserId,
  'notes' : IDL.Opt(IDL.Text),
  'cycleLength' : IDL.Nat,
  'symptoms' : IDL.Vec(IDL.Text),
  'startDate' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addMenstrualCycle' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Vec(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'addTestimonial' : IDL.Func([Testimonial], [IDL.Bool], []),
  'addWeekNote' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'bookAppointment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'cancelAppointment' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'createBlog' : IDL.Func([Blog], [IDL.Bool], []),
  'createDoctor' : IDL.Func([Doctor], [IDL.Bool], []),
  'createHealthPackage' : IDL.Func([HealthPackage], [IDL.Bool], []),
  'createHospital' : IDL.Func([Hospital], [IDL.Bool], []),
  'deleteBlog' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteDoctor' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteHospital' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteTestimonial' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAppointmentById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(Appointment)],
      ['query'],
    ),
  'getBlogById' : IDL.Func([IDL.Text], [IDL.Opt(Blog)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getDoctorById' : IDL.Func([IDL.Text], [IDL.Opt(Doctor)], ['query']),
  'getHealthPackage' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(HealthPackage)],
      ['query'],
    ),
  'getHospitalById' : IDL.Func([IDL.Text], [IDL.Opt(Hospital)], ['query']),
  'getMyPregnancyData' : IDL.Func([], [IDL.Opt(PregnancyData)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getReport' : IDL.Func([IDL.Text], [IDL.Opt(Report)], ['query']),
  'getUserById' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'listAllBlogs' : IDL.Func([], [IDL.Vec(Blog)], ['query']),
  'listAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'listAppointmentsByDoctor' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'listDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
  'listDoctorsByHospital' : IDL.Func([IDL.Text], [IDL.Vec(Doctor)], ['query']),
  'listDoctorsBySpeciality' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Doctor)],
      ['query'],
    ),
  'listHealthPackages' : IDL.Func([], [IDL.Vec(HealthPackage)], ['query']),
  'listHospitals' : IDL.Func([], [IDL.Vec(Hospital)], ['query']),
  'listHospitalsByCity' : IDL.Func([IDL.Text], [IDL.Vec(Hospital)], ['query']),
  'listMyAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'listMyMenstrualCycles' : IDL.Func([], [IDL.Vec(MenstrualCycle)], ['query']),
  'listMyReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'listPublishedBlogs' : IDL.Func([], [IDL.Vec(Blog)], ['query']),
  'listTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'listUsersByRole' : IDL.Func([UserRole], [IDL.Vec(User)], ['query']),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, UserRole, IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'updateAppointmentStatus' : IDL.Func(
      [IDL.Text, AppointmentStatus],
      [IDL.Bool],
      [],
    ),
  'updateBlog' : IDL.Func([Blog], [IDL.Bool], []),
  'updateDoctor' : IDL.Func([Doctor], [IDL.Bool], []),
  'updateHealthPackage' : IDL.Func([HealthPackage], [IDL.Bool], []),
  'updateHospital' : IDL.Func([Hospital], [IDL.Bool], []),
  'updateMenstrualCycle' : IDL.Func([MenstrualCycle], [IDL.Bool], []),
  'updateMyProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'updateSlotAvailability' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Bool],
      [],
    ),
  'uploadReport' : IDL.Func([Report], [IDL.Bool], []),
  'upsertPregnancyData' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Testimonial = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'patientName' : IDL.Text,
    'rating' : IDL.Nat,
    'department' : IDL.Text,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Blog = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'publishDate' : IDL.Text,
    'author' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const UserId = IDL.Text;
  const TimeSlot = IDL.Record({
    'id' : IDL.Text,
    'day' : IDL.Text,
    'startTime' : IDL.Text,
    'endTime' : IDL.Text,
    'isAvailable' : IDL.Bool,
  });
  const Doctor = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'hospitalIds' : IDL.Vec(IDL.Text),
    'userId' : UserId,
    'name' : IDL.Text,
    'qualifications' : IDL.Text,
    'speciality' : IDL.Text,
    'experience' : IDL.Nat,
    'imageUrl' : IDL.Opt(IDL.Text),
    'availableSlots' : IDL.Vec(TimeSlot),
    'rating' : IDL.Float64,
  });
  const HealthPackage = IDL.Record({
    'id' : IDL.Text,
    'tests' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Hospital = IDL.Record({
    'id' : IDL.Text,
    'emergency' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'state' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'address' : IDL.Text,
    'facilities' : IDL.Vec(IDL.Text),
    'phone' : IDL.Text,
    'doctorIds' : IDL.Vec(IDL.Text),
  });
  const AppointmentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Appointment = IDL.Record({
    'id' : IDL.Text,
    'status' : AppointmentStatus,
    'doctorId' : IDL.Text,
    'patientId' : UserId,
    'date' : IDL.Text,
    'createdAt' : Timestamp,
    'slot' : IDL.Text,
    'hospitalId' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'department' : IDL.Text,
  });
  const WeekNote = IDL.Record({
    'scanImageRef' : IDL.Opt(IDL.Text),
    'note' : IDL.Text,
    'week' : IDL.Nat,
  });
  const PregnancyData = IDL.Record({
    'id' : IDL.Text,
    'patientId' : UserId,
    'lastUpdated' : Timestamp,
    'currentWeek' : IDL.Nat,
    'notes' : IDL.Vec(WeekNote),
    'startDate' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'patient' : IDL.Null,
    'admin' : IDL.Null,
    'doctor' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'email' : IDL.Text,
    'abhaId' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
  });
  const Report = IDL.Record({
    'id' : IDL.Text,
    'doctorId' : IDL.Text,
    'patientId' : UserId,
    'date' : IDL.Text,
    'fileName' : IDL.Text,
    'reportType' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'fileRef' : IDL.Text,
  });
  const MenstrualCycle = IDL.Record({
    'id' : IDL.Text,
    'patientId' : UserId,
    'notes' : IDL.Opt(IDL.Text),
    'cycleLength' : IDL.Nat,
    'symptoms' : IDL.Vec(IDL.Text),
    'startDate' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addMenstrualCycle' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Vec(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'addTestimonial' : IDL.Func([Testimonial], [IDL.Bool], []),
    'addWeekNote' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'bookAppointment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'cancelAppointment' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'createBlog' : IDL.Func([Blog], [IDL.Bool], []),
    'createDoctor' : IDL.Func([Doctor], [IDL.Bool], []),
    'createHealthPackage' : IDL.Func([HealthPackage], [IDL.Bool], []),
    'createHospital' : IDL.Func([Hospital], [IDL.Bool], []),
    'deleteBlog' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteDoctor' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteHospital' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteTestimonial' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAppointmentById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Appointment)],
        ['query'],
      ),
    'getBlogById' : IDL.Func([IDL.Text], [IDL.Opt(Blog)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getDoctorById' : IDL.Func([IDL.Text], [IDL.Opt(Doctor)], ['query']),
    'getHealthPackage' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(HealthPackage)],
        ['query'],
      ),
    'getHospitalById' : IDL.Func([IDL.Text], [IDL.Opt(Hospital)], ['query']),
    'getMyPregnancyData' : IDL.Func([], [IDL.Opt(PregnancyData)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getReport' : IDL.Func([IDL.Text], [IDL.Opt(Report)], ['query']),
    'getUserById' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'listAllBlogs' : IDL.Func([], [IDL.Vec(Blog)], ['query']),
    'listAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'listAppointmentsByDoctor' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'listDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
    'listDoctorsByHospital' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Doctor)],
        ['query'],
      ),
    'listDoctorsBySpeciality' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Doctor)],
        ['query'],
      ),
    'listHealthPackages' : IDL.Func([], [IDL.Vec(HealthPackage)], ['query']),
    'listHospitals' : IDL.Func([], [IDL.Vec(Hospital)], ['query']),
    'listHospitalsByCity' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Hospital)],
        ['query'],
      ),
    'listMyAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'listMyMenstrualCycles' : IDL.Func(
        [],
        [IDL.Vec(MenstrualCycle)],
        ['query'],
      ),
    'listMyReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'listPublishedBlogs' : IDL.Func([], [IDL.Vec(Blog)], ['query']),
    'listTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'listUsersByRole' : IDL.Func([UserRole], [IDL.Vec(User)], ['query']),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, UserRole, IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'updateAppointmentStatus' : IDL.Func(
        [IDL.Text, AppointmentStatus],
        [IDL.Bool],
        [],
      ),
    'updateBlog' : IDL.Func([Blog], [IDL.Bool], []),
    'updateDoctor' : IDL.Func([Doctor], [IDL.Bool], []),
    'updateHealthPackage' : IDL.Func([HealthPackage], [IDL.Bool], []),
    'updateHospital' : IDL.Func([Hospital], [IDL.Bool], []),
    'updateMenstrualCycle' : IDL.Func([MenstrualCycle], [IDL.Bool], []),
    'updateMyProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'updateSlotAvailability' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'uploadReport' : IDL.Func([Report], [IDL.Bool], []),
    'upsertPregnancyData' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };