/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PregnancyData {
    id: string;
    patientId: UserId;
    lastUpdated: Timestamp;
    currentWeek: bigint;
    notes: Array<WeekNote>;
    startDate: string;
}
export interface MenstrualCycle {
    id: string;
    patientId: UserId;
    notes?: string;
    cycleLength: bigint;
    symptoms: Array<string>;
    startDate: string;
}
export type Timestamp = bigint;
export interface TimeSlot {
    id: string;
    day: string;
    startTime: string;
    endTime: string;
    isAvailable: boolean;
}
export interface User {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    email: string;
    abhaId?: string;
    phone: string;
}
export interface WeekNote {
    scanImageRef?: string;
    note: string;
    week: bigint;
}
export interface Report {
    id: string;
    doctorId: string;
    patientId: UserId;
    date: string;
    fileName: string;
    reportType: string;
    notes?: string;
    fileRef: string;
}
export type UserId = string;
export interface Hospital {
    id: string;
    emergency: string;
    city: string;
    name: string;
    state: string;
    imageUrl?: string;
    address: string;
    facilities: Array<string>;
    phone: string;
    doctorIds: Array<string>;
}
export interface Doctor {
    id: string;
    bio: string;
    hospitalIds: Array<string>;
    userId: UserId;
    name: string;
    qualifications: string;
    speciality: string;
    experience: bigint;
    imageUrl?: string;
    availableSlots: Array<TimeSlot>;
    rating: number;
}
export interface Appointment {
    id: string;
    status: AppointmentStatus;
    doctorId: string;
    patientId: UserId;
    date: string;
    createdAt: Timestamp;
    slot: string;
    hospitalId: string;
    notes?: string;
    department: string;
}
export interface HealthPackage {
    id: string;
    tests: Array<string>;
    name: string;
    description: string;
    isActive: boolean;
    category: string;
    price: bigint;
}
export interface Blog {
    id: string;
    title: string;
    content: string;
    isPublished: boolean;
    publishDate: string;
    author: string;
    imageUrl?: string;
    excerpt: string;
    category: string;
}
export interface Testimonial {
    id: string;
    content: string;
    patientName: string;
    rating: bigint;
    department: string;
}
export enum AppointmentStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    confirmed = "confirmed"
}
export enum UserRole {
    patient = "patient",
    admin = "admin",
    doctor = "doctor"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addMenstrualCycle(startDate: string, cycleLength: bigint, symptoms: Array<string>, notes: string | null): Promise<string>;
    addTestimonial(testimonial: Testimonial): Promise<boolean>;
    addWeekNote(week: bigint, note: string, scanImageRef: string | null): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    bookAppointment(doctorId: string, hospitalId: string, department: string, slot: string, date: string, notes: string | null): Promise<string>;
    cancelAppointment(id: string): Promise<boolean>;
    createBlog(blog: Blog): Promise<boolean>;
    createDoctor(doctor: Doctor): Promise<boolean>;
    createHealthPackage(pkg: HealthPackage): Promise<boolean>;
    createHospital(hospital: Hospital): Promise<boolean>;
    deleteBlog(id: string): Promise<boolean>;
    deleteDoctor(id: string): Promise<boolean>;
    deleteHospital(id: string): Promise<boolean>;
    deleteTestimonial(id: string): Promise<boolean>;
    getAppointmentById(id: string): Promise<Appointment | null>;
    getBlogById(id: string): Promise<Blog | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getDoctorById(id: string): Promise<Doctor | null>;
    getHealthPackage(id: string): Promise<HealthPackage | null>;
    getHospitalById(id: string): Promise<Hospital | null>;
    getMyPregnancyData(): Promise<PregnancyData | null>;
    getMyProfile(): Promise<User | null>;
    getReport(id: string): Promise<Report | null>;
    getUserById(id: UserId): Promise<User | null>;
    isCallerAdmin(): Promise<boolean>;
    listAllAppointments(): Promise<Array<Appointment>>;
    listAllBlogs(): Promise<Array<Blog>>;
    listAllUsers(): Promise<Array<User>>;
    listAppointmentsByDoctor(doctorId: string): Promise<Array<Appointment>>;
    listDoctors(): Promise<Array<Doctor>>;
    listDoctorsByHospital(hospitalId: string): Promise<Array<Doctor>>;
    listDoctorsBySpeciality(speciality: string): Promise<Array<Doctor>>;
    listHealthPackages(): Promise<Array<HealthPackage>>;
    listHospitals(): Promise<Array<Hospital>>;
    listHospitalsByCity(city: string): Promise<Array<Hospital>>;
    listMyAppointments(): Promise<Array<Appointment>>;
    listMyMenstrualCycles(): Promise<Array<MenstrualCycle>>;
    listMyReports(): Promise<Array<Report>>;
    listPublishedBlogs(): Promise<Array<Blog>>;
    listTestimonials(): Promise<Array<Testimonial>>;
    listUsersByRole(role: UserRole): Promise<Array<User>>;
    registerUser(name: string, email: string, phone: string, role: UserRole, abhaId: string | null): Promise<string>;
    updateAppointmentStatus(id: string, status: AppointmentStatus): Promise<boolean>;
    updateBlog(blog: Blog): Promise<boolean>;
    updateDoctor(doctor: Doctor): Promise<boolean>;
    updateHealthPackage(pkg: HealthPackage): Promise<boolean>;
    updateHospital(hospital: Hospital): Promise<boolean>;
    updateMenstrualCycle(cycle: MenstrualCycle): Promise<boolean>;
    updateMyProfile(name: string, phone: string, abhaId: string | null): Promise<boolean>;
    updateSlotAvailability(doctorId: string, slotId: string, isAvailable: boolean): Promise<boolean>;
    uploadReport(report: Report): Promise<boolean>;
    upsertPregnancyData(currentWeek: bigint, startDate: string): Promise<boolean>;
}
import type { Appointment as _Appointment, AppointmentStatus as _AppointmentStatus, Blog as _Blog, Doctor as _Doctor, HealthPackage as _HealthPackage, Hospital as _Hospital, MenstrualCycle as _MenstrualCycle, PregnancyData as _PregnancyData, Report as _Report, TimeSlot as _TimeSlot, Timestamp as _Timestamp, User as _User, UserId as _UserId, UserRole as _UserRole, UserRole__1 as _UserRole__1, WeekNote as _WeekNote } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addMenstrualCycle(arg0: string, arg1: bigint, arg2: Array<string>, arg3: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addMenstrualCycle(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMenstrualCycle(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async addTestimonial(arg0: Testimonial): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTestimonial(arg0);
            return result;
        }
    }
    async addWeekNote(arg0: bigint, arg1: string, arg2: string | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addWeekNote(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWeekNote(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bookAppointment(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.bookAppointment(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookAppointment(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async cancelAppointment(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelAppointment(arg0);
            return result;
        }
    }
    async createBlog(arg0: Blog): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.createBlog(to_candid_Blog_n4(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBlog(to_candid_Blog_n4(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createDoctor(arg0: Doctor): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.createDoctor(to_candid_Doctor_n6(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDoctor(to_candid_Doctor_n6(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createHealthPackage(arg0: HealthPackage): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.createHealthPackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHealthPackage(arg0);
            return result;
        }
    }
    async createHospital(arg0: Hospital): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.createHospital(to_candid_Hospital_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHospital(to_candid_Hospital_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteBlog(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlog(arg0);
            return result;
        }
    }
    async deleteDoctor(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDoctor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDoctor(arg0);
            return result;
        }
    }
    async deleteHospital(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHospital(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHospital(arg0);
            return result;
        }
    }
    async deleteTestimonial(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTestimonial(arg0);
            return result;
        }
    }
    async getAppointmentById(arg0: string): Promise<Appointment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentById(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentById(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogById(arg0: string): Promise<Blog | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogById(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogById(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDoctorById(arg0: string): Promise<Doctor | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctorById(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctorById(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHealthPackage(arg0: string): Promise<HealthPackage | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHealthPackage(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHealthPackage(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHospitalById(arg0: string): Promise<Hospital | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHospitalById(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHospitalById(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPregnancyData(): Promise<PregnancyData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPregnancyData();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPregnancyData();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReport(arg0: string): Promise<Report | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReport(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReport(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserById(arg0: UserId): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserById(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserById(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllAppointments();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllAppointments();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllBlogs(): Promise<Array<Blog>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllBlogs();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllBlogs();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllUsers();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllUsers();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAppointmentsByDoctor(arg0: string): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAppointmentsByDoctor(arg0);
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAppointmentsByDoctor(arg0);
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDoctors(): Promise<Array<Doctor>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDoctors();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDoctors();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDoctorsByHospital(arg0: string): Promise<Array<Doctor>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDoctorsByHospital(arg0);
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDoctorsByHospital(arg0);
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDoctorsBySpeciality(arg0: string): Promise<Array<Doctor>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDoctorsBySpeciality(arg0);
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDoctorsBySpeciality(arg0);
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async listHealthPackages(): Promise<Array<HealthPackage>> {
        if (this.processError) {
            try {
                const result = await this.actor.listHealthPackages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listHealthPackages();
            return result;
        }
    }
    async listHospitals(): Promise<Array<Hospital>> {
        if (this.processError) {
            try {
                const result = await this.actor.listHospitals();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listHospitals();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async listHospitalsByCity(arg0: string): Promise<Array<Hospital>> {
        if (this.processError) {
            try {
                const result = await this.actor.listHospitalsByCity(arg0);
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listHospitalsByCity(arg0);
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyAppointments();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyAppointments();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyMenstrualCycles(): Promise<Array<MenstrualCycle>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyMenstrualCycles();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyMenstrualCycles();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyReports(): Promise<Array<Report>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyReports();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyReports();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPublishedBlogs(): Promise<Array<Blog>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPublishedBlogs();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPublishedBlogs();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTestimonials();
            return result;
        }
    }
    async listUsersByRole(arg0: UserRole): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsersByRole(to_candid_UserRole_n51(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsersByRole(to_candid_UserRole_n51(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string, arg3: UserRole, arg4: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2, to_candid_UserRole_n51(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2, to_candid_UserRole_n51(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async updateAppointmentStatus(arg0: string, arg1: AppointmentStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppointmentStatus(arg0, to_candid_AppointmentStatus_n53(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppointmentStatus(arg0, to_candid_AppointmentStatus_n53(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateBlog(arg0: Blog): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlog(to_candid_Blog_n4(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlog(to_candid_Blog_n4(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateDoctor(arg0: Doctor): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDoctor(to_candid_Doctor_n6(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDoctor(to_candid_Doctor_n6(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateHealthPackage(arg0: HealthPackage): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHealthPackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHealthPackage(arg0);
            return result;
        }
    }
    async updateHospital(arg0: Hospital): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHospital(to_candid_Hospital_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHospital(to_candid_Hospital_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateMenstrualCycle(arg0: MenstrualCycle): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMenstrualCycle(to_candid_MenstrualCycle_n55(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMenstrualCycle(to_candid_MenstrualCycle_n55(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateMyProfile(arg0: string, arg1: string, arg2: string | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyProfile(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyProfile(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateSlotAvailability(arg0: string, arg1: string, arg2: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSlotAvailability(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSlotAvailability(arg0, arg1, arg2);
            return result;
        }
    }
    async uploadReport(arg0: Report): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadReport(to_candid_Report_n57(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadReport(to_candid_Report_n57(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async upsertPregnancyData(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertPregnancyData(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertPregnancyData(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AppointmentStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppointmentStatus): AppointmentStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Appointment_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Appointment {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Blog_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Blog): Blog {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Doctor_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Doctor): Doctor {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Hospital_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Hospital): Hospital {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_MenstrualCycle_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MenstrualCycle): MenstrualCycle {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_PregnancyData_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PregnancyData): PregnancyData {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Report_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Report): Report {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_User_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_WeekNote_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WeekNote): WeekNote {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Appointment]): Appointment | null {
    return value.length === 0 ? null : from_candid_Appointment_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Blog]): Blog | null {
    return value.length === 0 ? null : from_candid_Blog_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Doctor]): Doctor | null {
    return value.length === 0 ? null : from_candid_Doctor_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HealthPackage]): HealthPackage | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Hospital]): Hospital | null {
    return value.length === 0 ? null : from_candid_Hospital_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PregnancyData]): PregnancyData | null {
    return value.length === 0 ? null : from_candid_PregnancyData_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Report]): Report | null {
    return value.length === 0 ? null : from_candid_Report_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _AppointmentStatus;
    doctorId: string;
    patientId: _UserId;
    date: string;
    createdAt: _Timestamp;
    slot: string;
    hospitalId: string;
    notes: [] | [string];
    department: string;
}): {
    id: string;
    status: AppointmentStatus;
    doctorId: string;
    patientId: UserId;
    date: string;
    createdAt: Timestamp;
    slot: string;
    hospitalId: string;
    notes?: string;
    department: string;
} {
    return {
        id: value.id,
        status: from_candid_AppointmentStatus_n13(_uploadFile, _downloadFile, value.status),
        doctorId: value.doctorId,
        patientId: value.patientId,
        date: value.date,
        createdAt: value.createdAt,
        slot: value.slot,
        hospitalId: value.hospitalId,
        notes: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.notes)),
        department: value.department
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    content: string;
    isPublished: boolean;
    publishDate: string;
    author: string;
    imageUrl: [] | [string];
    excerpt: string;
    category: string;
}): {
    id: string;
    title: string;
    content: string;
    isPublished: boolean;
    publishDate: string;
    author: string;
    imageUrl?: string;
    excerpt: string;
    category: string;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        isPublished: value.isPublished,
        publishDate: value.publishDate,
        author: value.author,
        imageUrl: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.imageUrl)),
        excerpt: value.excerpt,
        category: value.category
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    bio: string;
    hospitalIds: Array<string>;
    userId: _UserId;
    name: string;
    qualifications: string;
    speciality: string;
    experience: bigint;
    imageUrl: [] | [string];
    availableSlots: Array<_TimeSlot>;
    rating: number;
}): {
    id: string;
    bio: string;
    hospitalIds: Array<string>;
    userId: UserId;
    name: string;
    qualifications: string;
    speciality: string;
    experience: bigint;
    imageUrl?: string;
    availableSlots: Array<TimeSlot>;
    rating: number;
} {
    return {
        id: value.id,
        bio: value.bio,
        hospitalIds: value.hospitalIds,
        userId: value.userId,
        name: value.name,
        qualifications: value.qualifications,
        speciality: value.speciality,
        experience: value.experience,
        imageUrl: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.imageUrl)),
        availableSlots: value.availableSlots,
        rating: value.rating
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    emergency: string;
    city: string;
    name: string;
    state: string;
    imageUrl: [] | [string];
    address: string;
    facilities: Array<string>;
    phone: string;
    doctorIds: Array<string>;
}): {
    id: string;
    emergency: string;
    city: string;
    name: string;
    state: string;
    imageUrl?: string;
    address: string;
    facilities: Array<string>;
    phone: string;
    doctorIds: Array<string>;
} {
    return {
        id: value.id,
        emergency: value.emergency,
        city: value.city,
        name: value.name,
        state: value.state,
        imageUrl: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.imageUrl)),
        address: value.address,
        facilities: value.facilities,
        phone: value.phone,
        doctorIds: value.doctorIds
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    patientId: _UserId;
    lastUpdated: _Timestamp;
    currentWeek: bigint;
    notes: Array<_WeekNote>;
    startDate: string;
}): {
    id: string;
    patientId: UserId;
    lastUpdated: Timestamp;
    currentWeek: bigint;
    notes: Array<WeekNote>;
    startDate: string;
} {
    return {
        id: value.id,
        patientId: value.patientId,
        lastUpdated: value.lastUpdated,
        currentWeek: value.currentWeek,
        notes: from_candid_vec_n31(_uploadFile, _downloadFile, value.notes),
        startDate: value.startDate
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scanImageRef: [] | [string];
    note: string;
    week: bigint;
}): {
    scanImageRef?: string;
    note: string;
    week: bigint;
} {
    return {
        scanImageRef: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.scanImageRef)),
        note: value.note,
        week: value.week
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    name: string;
    createdAt: _Timestamp;
    role: _UserRole;
    email: string;
    abhaId: [] | [string];
    phone: string;
}): {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    email: string;
    abhaId?: string;
    phone: string;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n37(_uploadFile, _downloadFile, value.role),
        email: value.email,
        abhaId: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.abhaId)),
        phone: value.phone
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    doctorId: string;
    patientId: _UserId;
    date: string;
    fileName: string;
    reportType: string;
    notes: [] | [string];
    fileRef: string;
}): {
    id: string;
    doctorId: string;
    patientId: UserId;
    date: string;
    fileName: string;
    reportType: string;
    notes?: string;
    fileRef: string;
} {
    return {
        id: value.id,
        doctorId: value.doctorId,
        patientId: value.patientId,
        date: value.date,
        fileName: value.fileName,
        reportType: value.reportType,
        notes: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.notes)),
        fileRef: value.fileRef
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    patientId: _UserId;
    notes: [] | [string];
    cycleLength: bigint;
    symptoms: Array<string>;
    startDate: string;
}): {
    id: string;
    patientId: UserId;
    notes?: string;
    cycleLength: bigint;
    symptoms: Array<string>;
    startDate: string;
} {
    return {
        id: value.id,
        patientId: value.patientId,
        notes: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.notes)),
        cycleLength: value.cycleLength,
        symptoms: value.symptoms,
        startDate: value.startDate
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
}): AppointmentStatus {
    return "cancelled" in value ? AppointmentStatus.cancelled : "pending" in value ? AppointmentStatus.pending : "completed" in value ? AppointmentStatus.completed : "confirmed" in value ? AppointmentStatus.confirmed : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    patient: null;
} | {
    admin: null;
} | {
    doctor: null;
}): UserRole {
    return "patient" in value ? UserRole.patient : "admin" in value ? UserRole.admin : "doctor" in value ? UserRole.doctor : value;
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WeekNote>): Array<WeekNote> {
    return value.map((x)=>from_candid_WeekNote_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appointment>): Array<Appointment> {
    return value.map((x)=>from_candid_Appointment_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Blog>): Array<Blog> {
    return value.map((x)=>from_candid_Blog_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Doctor>): Array<Doctor> {
    return value.map((x)=>from_candid_Doctor_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Hospital>): Array<Hospital> {
    return value.map((x)=>from_candid_Hospital_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MenstrualCycle>): Array<MenstrualCycle> {
    return value.map((x)=>from_candid_MenstrualCycle_n48(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Report>): Array<Report> {
    return value.map((x)=>from_candid_Report_n40(_uploadFile, _downloadFile, x));
}
function to_candid_AppointmentStatus_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus): _AppointmentStatus {
    return to_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function to_candid_Blog_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Blog): _Blog {
    return to_candid_record_n5(_uploadFile, _downloadFile, value);
}
function to_candid_Doctor_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Doctor): _Doctor {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_Hospital_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Hospital): _Hospital {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_MenstrualCycle_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MenstrualCycle): _MenstrualCycle {
    return to_candid_record_n56(_uploadFile, _downloadFile, value);
}
function to_candid_Report_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Report): _Report {
    return to_candid_record_n58(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    content: string;
    isPublished: boolean;
    publishDate: string;
    author: string;
    imageUrl?: string;
    excerpt: string;
    category: string;
}): {
    id: string;
    title: string;
    content: string;
    isPublished: boolean;
    publishDate: string;
    author: string;
    imageUrl: [] | [string];
    excerpt: string;
    category: string;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        isPublished: value.isPublished,
        publishDate: value.publishDate,
        author: value.author,
        imageUrl: value.imageUrl ? candid_some(value.imageUrl) : candid_none(),
        excerpt: value.excerpt,
        category: value.category
    };
}
function to_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    patientId: UserId;
    notes?: string;
    cycleLength: bigint;
    symptoms: Array<string>;
    startDate: string;
}): {
    id: string;
    patientId: _UserId;
    notes: [] | [string];
    cycleLength: bigint;
    symptoms: Array<string>;
    startDate: string;
} {
    return {
        id: value.id,
        patientId: value.patientId,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        cycleLength: value.cycleLength,
        symptoms: value.symptoms,
        startDate: value.startDate
    };
}
function to_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    doctorId: string;
    patientId: UserId;
    date: string;
    fileName: string;
    reportType: string;
    notes?: string;
    fileRef: string;
}): {
    id: string;
    doctorId: string;
    patientId: _UserId;
    date: string;
    fileName: string;
    reportType: string;
    notes: [] | [string];
    fileRef: string;
} {
    return {
        id: value.id,
        doctorId: value.doctorId,
        patientId: value.patientId,
        date: value.date,
        fileName: value.fileName,
        reportType: value.reportType,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        fileRef: value.fileRef
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    bio: string;
    hospitalIds: Array<string>;
    userId: UserId;
    name: string;
    qualifications: string;
    speciality: string;
    experience: bigint;
    imageUrl?: string;
    availableSlots: Array<TimeSlot>;
    rating: number;
}): {
    id: string;
    bio: string;
    hospitalIds: Array<string>;
    userId: _UserId;
    name: string;
    qualifications: string;
    speciality: string;
    experience: bigint;
    imageUrl: [] | [string];
    availableSlots: Array<_TimeSlot>;
    rating: number;
} {
    return {
        id: value.id,
        bio: value.bio,
        hospitalIds: value.hospitalIds,
        userId: value.userId,
        name: value.name,
        qualifications: value.qualifications,
        speciality: value.speciality,
        experience: value.experience,
        imageUrl: value.imageUrl ? candid_some(value.imageUrl) : candid_none(),
        availableSlots: value.availableSlots,
        rating: value.rating
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    emergency: string;
    city: string;
    name: string;
    state: string;
    imageUrl?: string;
    address: string;
    facilities: Array<string>;
    phone: string;
    doctorIds: Array<string>;
}): {
    id: string;
    emergency: string;
    city: string;
    name: string;
    state: string;
    imageUrl: [] | [string];
    address: string;
    facilities: Array<string>;
    phone: string;
    doctorIds: Array<string>;
} {
    return {
        id: value.id,
        emergency: value.emergency,
        city: value.city,
        name: value.name,
        state: value.state,
        imageUrl: value.imageUrl ? candid_some(value.imageUrl) : candid_none(),
        address: value.address,
        facilities: value.facilities,
        phone: value.phone,
        doctorIds: value.doctorIds
    };
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    patient: null;
} | {
    admin: null;
} | {
    doctor: null;
} {
    return value == UserRole.patient ? {
        patient: null
    } : value == UserRole.admin ? {
        admin: null
    } : value == UserRole.doctor ? {
        doctor: null
    } : value;
}
function to_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
} {
    return value == AppointmentStatus.cancelled ? {
        cancelled: null
    } : value == AppointmentStatus.pending ? {
        pending: null
    } : value == AppointmentStatus.completed ? {
        completed: null
    } : value == AppointmentStatus.confirmed ? {
        confirmed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
